### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by michaelboulton** [logdna/python#12]
Noticed a couple of things in the readme:

1. It makes reference to the MAC address/ip address in the 'setup' section but I can't see anywhere this is used in the code

2. The documentation for `LogDNAHandler` says the first option should be `key`, but in the code it's actually `token`

**Comment by respectus** [comment]
Hey @michaelboulton,

Appreciate you reporting the issues with the Readme. I've updated the logdna package accordingly, version 1.2.3 will have proper support for ip addresses and mac addresses. I have also updated the code to reflect that the argument passed to the LogDNA Handler is indeed referenced as key. We have the concept of an ingestion key and we wanted to keep the wording in the readme similar. Thanks for keeping up with the module, do let me know if you notice any issues with version 1.2.3.
