### ISSUE TITLE
gethostname not defined error

### ISSUE THREAD

**Issue by vinodsharma** [logdna/python#14]
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    test = LogDNAHandler(key, options)
  File "/home/vinod/work/venv_python3.6/lib/python3.6/site-packages/logdna/logdna.py", line 18, in __init__
    self.hostname = options['hostname'] if 'hostname' in options else gethostname()
NameError: name 'gethostname' is not defined
```
This is because `gethostname` is not imported. Easy fix is to call `socket.gethostname()`.

`self.hostname = options['hostname'] if 'hostname' in options else gethostname()`
should be replaced with
`self.hostname = options['hostname'] if 'hostname' in options else socket.gethostname()`
  
logdna version is 1.2.3

**Comment by respectus** [comment]
Hi @vinodsharma, Thanks for catching this oversight on my part. Really do appreciate the heads up on this, I've updated version 1.2.4 to use the proper reference to socket.gethostname(). Do let me know if this version doesn't work properly. Thanks!

**Comment by vinodsharma** [comment]
This issue is not observed in 1.2.4. Thanks, @respectus for the prompt action.
