### ISSUE TITLE
NameError: name 'gethostname' is not defined

### ISSUE THREAD

**Issue by tadas-subonis** [logdna/python#15]
The function gethostname doesn't exist on python3.6

```
     log_dna = LogDNAHandler('5c0924a736cc432b89a7a961ac9b2bec')
   File "/usr/local/lib/python3.6/site-packages/logdna/logdna.py", line 18, in __init__
     self.hostname = options['hostname'] if 'hostname' in options else gethostname()
 NameError: name 'gethostname' is not defined
```

**Comment by respectus** [comment]
Hi @tadas-subonis, thanks for reporting this bug. The issue has been resolved in the latest version of the module logdna 1.2.4. Please let me know if you experience any problems with version 1.2.4 thanks!
