### ISSUE TITLE
How can I cerate a log config file using logdna

### ISSUE THREAD

**Issue by datavisorzhenbangliu** [logdna/python#20]
How Can I create the log config file as following file:

`[loggers]
keys=root

[handlers]
keys=stream_handler

[formatters]
keys=formatter

[logger_root]
level=DEBUG
handlers=stream_handler

[handler_stream_handler]
class=StreamHandler
level=DEBUG
formatter=formatter
args=(sys.stderr,)

[formatter_formatter]
format=%(asctime)s %(name)-12s %(levelname)-8s %(message)s`

**Comment by smusali** [comment]
@datavisorzhenbangliu, I think this is not the place for this question - even if it is, we do not support config file for our `Python` library.
