### ISSUE TITLE
RecursionError when queue full and LogDNA can't be reached

### ISSUE THREAD

**Issue by theY4Kman** [logdna/python#21]
If a new log message is emitted while the handler's queue size meets the [hard-coded](https://github.com/logdna/python/blob/master/logdna/logdna.py#L38) [1MB limit](https://github.com/logdna/python/blob/master/logdna/configs.py#L10), it attempts to [flush all messages to LogDNA in the same thread as the logger](https://github.com/logdna/python/blob/master/logdna/logdna.py#L61-L62). If the messages can't successfully be sent to LogDNA's servers (due to connectivity issues, maybe invalid auth, perhaps I forgot to fill the tank with internet juice, possibly aliens — [_probably aliens_](# "definitely aliens")), exceptions cause more log messages — and because the queue couldn't be flushed, it's still over the queue size limit, so the handler attempts to flush immediately in the same thread. Eventually, the number of frames exceeds `sys.getrecursionlimit()` and a `RecursionError` is thrown. Once a connection can be established, the queue can be drained, and it's all quiet on the western front.

**Comment by LYHuang** [comment]
Should be fix in the version `1.2.9`, thank you for reporting issue!

**Comment by smusali** [comment]
@theY4Kman, fixed [here](https://github.com/logdna/python/commit/6dcd47d29775e3e2e070b4f9f210cce9aabaaba5), thanks to @LYHuang!
