### ISSUE TITLE
request post does not timeout

### ISSUE THREAD

**Issue by btashton** [logdna/python#5]
There is no timeout parameter being used on the requests post.  If there is a connection issue when flushing the logs the application can lock forever.  I am happy to send a merge request, but I am not quite sure what the ideal solution is here. 

One thought I had was to just defer the flush after a timeout.   If we do that I think the buffer should continue to grow until MAX_BUF_BYTE_LIMIT.  Once this is hit log messages just keep getting dropped.   Another option would be to keep dropping the oldest messages until the buffer is small enough.

**Comment by respectus** [comment]
Hi @btashton, thanks for bringing up this issue. In release 1.0.6 I've added a 30 second timeout to post requests and I've wrapped it in a try catch to print the errors that might occur during transit. If the buffer is full and there are persistent network connection issues, the module will attempt to keep on appending to the buffer and then immediately flush. The byte limit set in the module is pretty far from the max bytes a request can post, so you should see several error messages before any logs are dropped. Appreciate you bringing this to our attention, please let me know if you experience any issues with this version, thanks!
