### ISSUE TITLE
Retry issue on Celery task

### ISSUE THREAD

**Issue by samims** [logdna/python#59]
When running celery(python 2.7) on django  getting the issue `Starting new HTTPS connection (1): logs.logdna.com`  hampering celery tasks. Traceback shows its because if `urllib` `Retry` which is being used by this library. Can anyone please help regarding this?

**Comment by smusali** [comment]
@cuu508, sorry for the late response!

#70 introduces the explicit retry mechanism and the changes have already been released in [`v1.17.0`](https://github.com/logdna/python/releases/tag/v1.17.0).

Please, let us know if you are still having the same issue or have any additional questions!

Thanks for using LogDNA!

_Happy Logging!_
