### ISSUE TITLE
Can buffer flush happen asynchronously?

### ISSUE THREAD

**Issue by cuu508** [logdna/python#61]
I'm troubleshooting a Django app that uses the `logdna.LogDNAHandler` log handler, and from time to time experiences long request latencies for no apparent reason.

Looking at `logdna.py`, I'm starting to suspect that LogDNAHandler might sometimes flush its buffer synchronously:

- if the buffer_log can acquire a lock
- and if `buf_size >= self.flush_limit` then it runs`flush()` then and there.
- and if `flush()` can acquire a lock, it runs a HTTP POST to LogDNA API

I tried to reproduce this locally: 

- I set `flush_limit` to a low value to cause the buffer to get full quickly
- I started a Django project from scratch, and added a single view:

```
logger = logging.getLogger("abc")


def hello(request):
    logger.info(
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus posuere sit amet orci eget feugiat. "
    )
    return HttpResponse("Hello World!")
```

I expect the above `logger.info(...)` call to always return quickly, so as not to delay the response to the client. But, when I run it,

![image](https://user-images.githubusercontent.com/661859/96600172-56f53800-12f9-11eb-86d3-891adb0bfcc8.png)

The second request takes 795ms, presumably because the view was waiting for LogDNAHandler to flush.

Is this working as designed or is there a bug?

**Comment by smusali** [comment]
@cuu508, sorry for the late response!

#70 introduces the usage of [`ThreadPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) which brings asynchronicity and the changes have already been released in [`v1.17.0`](https://github.com/logdna/python/releases/tag/v1.17.0).

Please, let us know if you have any additional questions!

Thanks for using LogDNA!

_Happy Logging!_
