### ISSUE TITLE
Breaking Change between 1.16 and 1.17/18

### ISSUE THREAD

**Issue by blaza1** [logdna/python#74]
**Issue:**

We have upgraded the logdna library from 1.16 to 1.18 and it now fails to logdna.

**Steps to reproduce:**

Run the following in the docker image python:3.7.11-stretch bash and logdna 1.18 installed.

```python
import logging
from logdna import LogDNAHandler

key='mysecurekey'

log = logging.getLogger('logdna')
log.setLevel(logging.INFO)

options = {
  'hostname': 'pytest',
  'ip': '10.0.1.1',
  'mac': 'C0:FF:EE:C0:FF:EE'
}

# Defaults to False; when True meta objects are searchable
options['index_meta'] = True

test = LogDNAHandler(key, options)

log.addHandler(test)

log.warning("Warning message", {'app': 'bloop'})
log.info("Info message")
```

No messages will appear on logdna.

Run the same script with logdna 1.16 and it will successfully log to logdna.

**Investigation:**
I did a diff between 1.16 and 1.18 and there is a big move to using multiple threads. Could this be a cause for logdna breaking for us ?

Please let me know if you would like any extra info.

**Comment by blaza1** [comment]
Just to add I tried logdna 1.18 in the image python:3.9.6-buster in case it was our outdated version of python which was causing images.

Any help will be greatly appreciated. Logdna has been a really useful tool for our company.

**Comment by gediminasz** [comment]
Can confirm. We recently upgraded from 1.16 to 1.18 as well and we stopped seeing our logs on logdna.com. We are using `python:3.8-slim-buster`.

**Comment by esatterwhite** [comment]
@blaza1 Yes, 1.17 introduced thread pools. Likely where the problem started.
Will do some digging here.

**Comment by esatterwhite** [comment]
@blaza1 I'm still investigating, but I can confirm that there is an issue here. The package seems to function properly when executed in a regular shell context. When it is executed in a docker container, the work isn't being scheduled correctly. I haven't quite narrowed where it is going wrong or why just yet.

I'm attaching some process traces for history and some additional eyes
[logdna.txt](https://github.com/logdna/python/files/7107490/logdna.txt)

I can see the logging calls being submitted to the worker pool, working on the root. It looks like it might be a problem in the python thread pool. I've only found a single report of this problem in the wild but no resolutions. 

I will keep digging and keep you all posted on progress.

**Comment by suddenkiss** [comment]
when I use flash + gunicorn gevent
1.18 sent a lot of duplicate logs
but 1.16 is not
it's may be a related issue

**Comment by serivt** [comment]
I think the problem occurs when writing to secondary, if I remove these lines the message is sent to logdna:
https://github.com/logdna/python/blob/398e82f6d46db00f895cc94612751e0c559c2aaa/logdna/logdna.py#L138-L139
I think it is necessary to change the size of the buffer when it is added to the secondary list
https://github.com/logdna/python/blob/398e82f6d46db00f895cc94612751e0c559c2aaa/logdna/logdna.py#L119-L120
