### ISSUE TITLE
Feature request: returning the LogDNA API replies

### ISSUE THREAD

**Issue by aufbakanleitung** [logdna/python#80]
So if I communicate with the LogDNA API through postman, posting a log line returns this:
```
{
    "status": "ok",
    "batchID": "611c8c7b-161c-43b8-88c3-3d90500070af:65281:ld86"
}
```
But if I post a log line through this library it returns nothing.
```python
response = logdna.info("Hello")
print(response)
# None
```
This is a problem, because currently my Cloud Function (lambda) is working locally, but in the cloud the log messages aren't coming through. In order to debug I'd like to know what the LogDNA API is returning.

**Comment by aufbakanleitung** [comment]
So I looked into creating a PR, but it's a bit difficult to figure out. I think in _logdna.py_ the  `try_request(self)` function and `send_request(self, data)` function should have all `return True` statements be `return response` instead. It should still work because an `if response` still evaluates to `True`. 

However I don't know  how to pass it on all the way to `logdna.info()`. If I look it goes into `__init__.py` then `info()` -> `_log()` -> `handle()` -> `callHandlers()` -> ???

**Comment by aufbakanleitung** [comment]
I was unable to do it, and I've refactored my code to work directly with the requests package.

```python

def post_curl(log, event, level="INFO", line="Login"):
    key = event['INGESTION_KEY']
    hostname = event['LOGDNA_IDENTITY']
    url = "https://logs.eu-de.logging.cloud.ibm.com/logs/ingest?hostname=" + hostname
    payload = {"lines": [{
           "line": line,
           "app": "cloud-function",
           "level": level,
           "env": "iclip-non-prod",
           "meta": log
         }]}

    response = requests.post(url, json=payload, auth=HTTPBasicAuth('INGESTION_KEY', key))
    return response.text
```

**Comment by dkhokhlov** [comment]
@aufbakanleitung 
do you need this for some kind of troubleshooting?
what about if the response will be logged?
